### ISSUE TITLE
numba support request

### ISSUE THREAD

**Issue by ebo** [orbingol/NURBS-Python#103]
I have read a couple of references to initial efforts to provide numba support to NURBS-Python.  If these repositories can be shared I have a little time I can spend on helping to get it, the test suites, and timing tests running.

**Comment by orbingol** [comment]
I am sorry but sharing might not be possible due to some limitations with a publication. Maybe later but not soon.

**Comment by ebo** [comment]
On Jul 22 2020 11:55 PM, Onur R. Bingol wrote:
> I am sorry but sharing might not be possible due to some limitations
> with a publication. Maybe later but not soon.

understand.  Please email me when/if it is released.  As a note, I 
would be willing to sign an NDA, but I have worked with academics for 
decades and understand the need to publish first...

**Comment by ebo** [comment]
Just checking in 9 months later.  Any news?
