### ISSUE TITLE
Evaluate surface at specific values of U and V 

### ISSUE THREAD

**Issue by VAero-Lab** [orbingol/NURBS-Python#104]
Hi !
I would like to know how to evaluate a B-spline surface at specific values of **u** and **v**? For instance, u=0,v=0.5. Is that possible?
Thanks

**Comment by orbingol** [comment]
It is `Surface.evaluate_single`, e.g. `surf.evaluate_single((0.0, 0.5))` for `u=0.0` and `v=0.5`. For future reference, `param` is a `float` for curves, `tuple` for surfaces and volumes for geomdl v5.x

Please refer to the documentation and the examples repository for more details.

**Comment by VAero-Lab** [comment]
Thank you ! Everything works fine
