### ISSUE TITLE
[question] Find intersection between surface and ray?

### ISSUE THREAD

**Issue by momba98** [orbingol/NURBS-Python#110]
Hey. Great repo. 

I got a very basic question: is it possible to validate the point where there is an intersection between a surface (it doesn't matter if it's Bezier or NURBS) and a ray?

I searched for something like this in exemples repo but I wasn't able to find.

**Comment by orbingol** [comment]
There are no intersection (surface-surface, surface-curve, surface-ray, and others) algorithms included in the library as of today
