### ISSUE TITLE
How to get the Y value of a  specific X point in B-spline curve

### ISSUE THREAD

**Issue by Peanut-Git2** [orbingol/NURBS-Python#114]
Thanks for your working first!
I have read the example about  [how to interpolate curve ](https://nurbs-python.readthedocs.io/en/latest//fitting-2.py)
I can get a series (x,y) value when I set the `curve.delta`, and use `curve.evalpts`. And I have read the[ docs](https://nurbs-python.readthedocs.io/en/latest/module_bspline.html?highlight=spline%27%3D#b-spline-curve) clearly.

But I don't know how to get or calculate y value when I give the curve (geomdl.BSpline.Curve) one specific x value. For example, I want to know y when x is -2.1 in this [example](https://nurbs-python.readthedocs.io/en/latest//fitting-2.py). 

```
from geomdl import fitting
from geomdl.visualization import VisMPL as vis
import numpy as np
import matplotlib.pyplot as plt

# The NURBS Book Ex9.1
points = ((0, 0), (3, 4), (-1, 4), (-4, 0), (-4, -3))
degree = 3  # cubic curve

# Do global curve interpolation
curve = fitting.interpolate_curve(points, degree)
curve.delta = 0.1

# I can get all (x,y) data
evalpts = np.array(curve.evalpts)

# But how to get y when I give x, just like this ???
# y_value = curve.calcaulte_x(x=-2.1)

```

**Comment by orbingol** [comment]
`geomdl` does not provide a method for those kinds of queries. However, you could use mathematical optimization methods or maybe ray intersection (should be easy to implement for a 2D curve) to query `y` from `x` values.
