### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by germa89** [orbingol/NURBS-Python#144]
I'm working in a project that one of the requirements is this package. We want to put our package is conda, but it seems it is easier to do this if all the packages dependencies are in conda already. 

So I'm happy to do the recipe if any of you agrees to be the maintainer (mainly you will be cited in their page as maintainer)

**Comment by orbingol** [comment]
@germa89 already there: https://anaconda.org/orbingol/geomdl

The recipes are under `conda` directory of this repo. Please refer to the CI configuration for `conda build` instructions. Install instructions are [here](https://github.com/orbingol/NURBS-Python#installation).

**Comment by germa89** [comment]
@orbingol would it be possible to have in conda-forge too? 

https://conda-forge.org/
https://github.com/conda-forge/staged-recipes

**Comment by orbingol** [comment]
Sure, feel free to submit the package request to conda-forge.

**Comment by germa89** [comment]
Thank you! I will do it shortly!
