### ISSUE TITLE
numpy v1.24 compatibility

### ISSUE THREAD

**Issue by davegelwan** [orbingol/NURBS-Python#161]
**Describe the bug**
This repo is not compatible with latest numpy version (v1.24)

VisConfig class uses a deprecated numpy data type (np.float).   That data type was **removed** in the latest version of numpy (v1.24).  VisConfig code should be updated to use np.float32 or np.float64, see:
https://github.com/orbingol/NURBS-Python/blob/5.x/geomdl/visualization/VisMPL.py#L71

**To Reproduce**
1. pip install numpy --upgrade
2. use VisMPL

**Expected Behavior**
Compatible with latest numpy version (v1.24)

**Configuration:**
 - OS: Windows 10
 - Python distribution: Python 3.10 with Numpy v1.24
 - geomdl install source:  pip
 - geomdl version/branch: geomdl v5.3.1

**Comment by orbingol** [comment]
Unfortunately, this is not fixable as of `v5.3.1` or any `v5.x` release. `v5.x` promises Python 2.7.x support. I am aware Python 2 has been EOL for a long time, but some academic code may still use older Python versions. There is also an issue with the Matplotlib support, you might need to install an older version of Matplotlib.

Just in case for the future reference, I am planning to use the [VFX reference platform](https://vfxplatform.com/) as a way to standardize the dependency support. I am open to suggestions for sure, but that reference platform is actually what I have been using for the last year for my other projects.

**Comment by greyltc** [comment]
Is it right to say that this needs a 6.x release to fix and closing it as "not planned" means there will be no 6.x release?
