### ISSUE TITLE
Calculate cubic splines that best fit the nurbs curves to a tolerance

### ISSUE THREAD

**Issue by goatchurchprime** [orbingol/NURBS-Python#22]
This one is more of a challenge (but worth doing).  

It would mean that DXF (which contains nurbs) to SVG (which only does cubic splines) will work perfectly.  

(BTW, nurbs are an annoyance in CADCAM; cubic splines are smooth enough for all purposes, because you can make them as short as you need to, the GUIs are no longer restricted to moving one control point at a time, and any CAM process needs to turn everything to flat segments before it can work -- you don't get splines in G-code.)

**Comment by orbingol** [comment]
Currently, I don't have any plans to implement this feature
