### ISSUE TITLE
Can't Import Fitting Module

### ISSUE THREAD

**Issue by Mitch981521** [orbingol/NURBS-Python#42]
**Describe the bug**

After installing NURBS-Python using pip, when I try to import the "fitting" module, I get an error saying "cannot import name fitting"

**To Reproduce**
1. Execute "pip install geomdl" install command
2. Copy or download the following example from NURBS-Python_Examples:   NURBS-Python_Examples/fitting/interpolation/global_surface.py
3. Run the File

**Expected Behavior**
I expected the file to run with a visualization of the approximated surface

**Configuration:**
 - OS: Ubuntu 16.04
 - Python distribution: OS default
 - Python version: 2.7.12
 - geomdl install source: "pip install geomdl" command
 - geomdl version/branch: 4.4.4

**Screenshots (Optional)**

**Additional Details (Optional)**
StackOverFlow says that it may be due to circular dependencies?

**Comment by orbingol** [comment]
Fitting module is not available in v4.x. Try installing the latest beta version of v5.x, e.g. `pip install geomdl==5.0b7`

You can find the list of releases here: https://pypi.org/project/geomdl/#history

**Comment by orbingol** [comment]
I've released geomdl v5.0.0 today. `pip install geomdl` should install the latest version correctly.

**Comment by Mitch981521** [comment]
thank you
