### ISSUE TITLE
Normal vectors to curves are incorrect.

### ISSUE THREAD

**Issue by carthurs** [orbingol/NURBS-Python#49]
Normals to curves are incorrect.

I've created a patch for this - basically the assumption in `_operations.py` under `normal_curve_single()` is false: `# 2nd derivative of the curve gives the normal`

The patch only addresses this one case, but I'm sure the bug occurs elsewhere in the library. Happy to provide what I've done.

Unpatched output, plotting the normals at 3 points on a curve:
![image](https://user-images.githubusercontent.com/11784292/58876231-5a1c6380-86c5-11e9-8081-f2047f04d76a.png)

Patched output, plotting the normals at the same 3 points on the same curve:
![image](https://user-images.githubusercontent.com/11784292/58876180-38bb7780-86c5-11e9-8b51-7713553e9a95.png)

**Comment by orbingol** [comment]
Would you also check if it occurs any other place and make a PR against `devmaster` branch?

**Comment by carthurs** [comment]
PR #50 made - I think there's still work to do, but it fixes that one case and should not impact other cases (i.e. 3D curves). Probably need a fix in 3D too.
