### ISSUE TITLE
How to save Surface as CAD Support file IGS/STEP ?

### ISSUE THREAD

**Issue by selvakarna** [orbingol/NURBS-Python#70]
How to save Surface as CAD Support file IGS/STEP ?

**Comment by orbingol** [comment]
Exporting to IGES and STEP feature is still work-in-progress.

**Comment by selvakarna** [comment]
Can you share sample of step export from surface or mesh ? 

algorithms?

**Comment by orbingol** [comment]
I don't think it is wise to share a bunch of undocumented Python and C++ code and expect people to figure out what is what. If you are in rush, you may want to check [STEPcode](https://github.com/stepcode/stepcode). STEPcode is unrelated with geomdl, so please refer to their documentation for more details.

**Comment by silentmissile** [comment]
you can try to use FreeCAD

https://anaconda.org/search?q=freecad
the package follows newest Anaconda

here is some example code, you can refer to it
https://forum.freecadweb.org/viewtopic.php?f=22&t=38218&p=325619&sid=903589966cb65fc527f65ce3c1812b1a#p325619

or you can try pythonocc
https://github.com/tpaviot/pythonocc-core

it has some recent comments, but the last formal release was 2 years ago, and I tried to install it by the latest Anaconda, but failed. By my test only Anaconda 5.2 is compatible with it

**Comment by selvakarna** [comment]
Hi @silentmissile , above link also have issue in installation .

https://forum.freecadweb.org/viewtopic.php?f=22&t=38218&p=325619&sid=903589966cb65fc527f65ce3c1812b1a#p325619

or you can try pythonocc
https://github.com/tpaviot/pythonocc-core

**Comment by orbingol** [comment]
I am guessing that this issue is somewhat resolved. Hopefully, I will also release an option for exporting/importing IGES and STEP files very soon :)
