### ISSUE TITLE
How to move the nurbs arc?

### ISSUE THREAD

**Issue by friends110110** [orbingol/NURBS-Python#77]
I provide some specific points,  using `interpolate_curve(points, degree) ` to generate a curve, 
now I wanna modify the  start point  and end point of the specific points, and make the nurbs  curve move smoothly entirety not only the start point and end point.  How to do that it ?  as the following image, move to another position . Please provide the code, thanks

![image](https://user-images.githubusercontent.com/3381671/75428527-4b788980-5983-11ea-8739-cd2fa64a6414.png)

**Comment by orbingol** [comment]
@friends110110 have you tried translating the control points? `linalg` module might also be helpful for that purpose.

**Comment by friends110110** [comment]
@orbingol Thanks for your reply.
I have no data about the translation of the control points ,  it only provide the translation of two interpolate points  ( which are start and end points) , 
could u provide some code about translate endpoint of the arc according to the interpolate nurbs curve?

**Comment by friends110110** [comment]
@orbingol could you give some advices?

**Comment by orbingol** [comment]
`interpolate_curve` creates control points and knot vectors for a given degree. By default, it creates a clamped curve (or knot vector), which means start and end points of the curve are clamped to the control points polygon.

There is also a way to translate the whole curve using `operations.translate` function.

**Comment by friends110110** [comment]
@orbingol now I have a nurbs curve , could you give me the examples about translate  the start point and end point  ,the the whole nurbs curve moves,  and  ignore the degree and knot vectors parameters ?

**Comment by orbingol** [comment]
@friends110110 I am trying to understand question but it doesn't make sense.

The start point of a clamped curve is the 1st element in the control points array and the end point of a clamped curve is the last element in the control points array. You may use `linalg.point_translate` to move those points using a vector. Then, you need to re-evaluate the curve.

For `operations.translate`, please refer to the examples repository. You may want to take a look at examples splitting the curve by knot insertion and moving one of the split curves using a vector.

**Comment by friends110110** [comment]
@orbingol  how to only add offset of the start and end points , and the other points on the nurbs curve2 move regularly automatically?

**Comment by orbingol** [comment]
There is no automatic way to do that as of geomdl v5.2.9. Like I said in https://github.com/orbingol/NURBS-Python/issues/79#issuecomment-596212178, you will need to implement offsetting algorithms and adapt them to your specific conditions. There may be other ways to solve your problem but you will still need to implement them.

**Comment by friends110110** [comment]
@orbingol  could u give some advices to help me to realize this function?

**Comment by orbingol** [comment]
Unfortunately, offsetting keyword might be the only lead I could give to you. I am pretty sure that you will find several research papers on curve offsetting.

Since geomdl does not include any offsetting algorithms as of v5.2.9, I'd like to consider this issue as solved.
