### ISSUE TITLE
How to generate nurbs curve according another curve?

### ISSUE THREAD

**Issue by friends110110** [orbingol/NURBS-Python#79]
How to generate nurbs curve2 according to :
1.the nurbs curve1 (which using the interpolate points  `interpolate_curve(points, degree)`) , 
2. the start point and end point on the nurbs curve2 ( which are translated from the start point and end point on the nurbs curve1 by add DELTA variance )?

something is similar to [this](https://github.com/orbingol/NURBS-Python/issues/77)
![image](https://user-images.githubusercontent.com/3381671/76139917-380aa400-6090-11ea-9029-2e240cba9708.png)

**Comment by orbingol** [comment]
This looks like offsetting but you seem to have some special conditions. There are no offsetting algorithms included in `geomdl` (I'd say yet, hopefully I will add in future)

**Comment by friends110110** [comment]
@orbingol  I wanna to generate nurbs curve2  according to nurbs curve1,  according to nurbs curve1's   start point and end point by adding offset,  do you have some solutions?

Not easy move the start and end points, other points will move regular along with the curve

**Comment by orbingol** [comment]
Related to #77
