### ISSUE TITLE
How to realize the curve of equidistant amplification

### ISSUE THREAD

**Issue by friends110110** [orbingol/NURBS-Python#81]
How to realize the curve of equidistant amplification ?  what code provide?
![image](https://user-images.githubusercontent.com/3381671/77131635-421ca180-6a97-11ea-9c7e-19ddadcdc9a8.png)

**Comment by orbingol** [comment]
I don't think `geomdl` has this feature. I'd suggest using the email list `nurbs-python@googlegroups.com` for features not implemented in `geomdl`.
