### ISSUE TITLE
Using discrete character points to generate offset parallel curve?

### ISSUE THREAD

**Issue by friends110110** [orbingol/NURBS-Python#82]
When I give discrete character points curve, how to generate offset parallel curve ? 
likes this
[this](https://i.stack.imgur.com/VMmLT.png)
 Does some java library or python library and examples to provide?

**Comment by orbingol** [comment]
I don't think `geomdl` has this feature. I'd suggest using the email list `nurbs-python@googlegroups.com` for features not implemented in `geomdl`.
