### ISSUE TITLE
Is there any function to compare two curves or surfaces？

### ISSUE THREAD

**Issue by zhxd050946** [orbingol/NURBS-Python#83]
Dear Bingol，

Thank you for your great job, NURBS_Python, which has saved me a lot of time. 

I want to compute the minimum distance from a point to a NURBS surface and the integral of volume between two BSpline or NURBS surfaces.

Are there any convenient method？

Looking forward for your reply.

**Comment by orbingol** [comment]
@zhxd050946 `geomdl` does not have the features you asked as of v5.2.9

I am closing this issue as it looks like it is related to #78
