### ISSUE TITLE
How to move the scaled point and keep the shape of the curve?

### ISSUE THREAD

**Issue by friends110110** [orbingol/NURBS-Python#93]
For a curve, I wanna move the start and end point to new position,  and then how to keep the shape of the curve ?

![image](https://user-images.githubusercontent.com/3381671/83091228-4be10780-a0cd-11ea-82a0-bf0cfb2e93dc.png)

From the points which circulated on the yellow curve,  move them to red curve position which circulated on the red curve, how to keep the shape of the curve on the red curve ?

**Comment by friends110110** [comment]
@orbingol @cshorler @heczis @Nodli Could you help me to solve this problem? move the start and end point of a curve to another position, how to keep the shape of new curve ?

**Comment by friends110110** [comment]
@orbingol could you help me to solve this problem?
Thank you

**Comment by orbingol** [comment]
@friends110110 this is not directly related to geomdl, like a bug or something else. Due to time constraints, I can't help you. I am closing this issue.
