### ISSUE TITLE
How to get fitting coefficients?

### ISSUE THREAD

**Issue by shz224** [orbingol/NURBS-Python#95]
Thanks for the convenient package. I wonder if I can extract the coefficients of a curve or surface fitting.

**Comment by orbingol** [comment]
@Jshcht There are some functions for this purpose in `fitting.py`. I'd suggest you looking at line 509. They are actually documented but not exported to the online documentation.

**Comment by shz224** [comment]
Thanks a lot for your kind rely and providing such a convenient package. I will check it out.

**Comment by orbingol** [comment]
I am closing this issue and marking it as resolved.
