### ISSUE TITLE
B-spline .normal returns only X&Y Z is always 0.0

### ISSUE THREAD

**Issue by Burtski** [orbingol/NURBS-Python#97]
It appears that BSpline.Curve.normal is only returning 2 dimensions instead of 3

I have a 3D BSpline (imported from Solidworks).
It appears that the .normal is only returning the X&Y components of the normal.
The Z component seems to be clamped to 0.00.

The .tangent vectors appears to be correct as well as the first and second derivatives.

NormalPoint,NormalVector = CenterCurve.normal(position)
Normal Vector = [-0.707107  0.707107  0.000000]

I expect it to be ~[-0.003486 -0.003486 -0.999988]

Windows 10, Python 3.7.4

**Comment by orbingol** [comment]
Using the information given, it is impossible to reproduce the problem. Please use the bug reporting template and complete all the information required.
