### ISSUE TITLE
Nurbs equally spaced points

### ISSUE THREAD

**Issue by andreabonacini** [orbingol/NURBS-Python#99]
Hi, 
i'm using the Nurbs.curve class and i would like to get a set of equally spaced evaluated points over the curve, possibly as a function of an imposed delta (or sample size). Is it possibile?
Regards,
Andrea

**Comment by orbingol** [comment]
Evaluated points are equally spaced on the parametric space (UVW) where the evaluation happens. It might or might not be equally spaced on the XYZ space.

**Comment by andreabonacini** [comment]
So, is there a function inside the NURBS library in order to compute equally spaced samples on the XYZ space? The input of the function i would like to be progress step previewsly defined in the XYZ space

**Comment by ebo** [comment]
@andreabonacini, are you referring to arc-length parameterization of the NURB?  ie. if you have a curve that is 6" long, and you evaluate it a 1" that it is 1/6'th of the way along the curve, or are you referring to something else?

**Comment by andreabonacini** [comment]
I was referring to if there was a method that takes as input a constant velocity (or a progress step) in order to obtain in output the parameter values that allow to have equally spaced points (cartesian coordinate) along the NURBS. Obviusly the parametrization u would not be equally spaced. 

Anyway, for that purpose i successfully implemented my own algorithm of a constant feed rate. This solved the problem for me.

**Comment by ebo** [comment]
I would be interested in looking at it if you would be willing to 
share.

**Comment by orbingol** [comment]
> Anyway, for that purpose i successfully implemented my own algorithm of a constant feed rate. This solved the problem for me.

I think we can close this issue.
